name: Publish SFU image

on:
  workflow_dispatch:
  push:
    branches: ['UE5.5']
    paths: ['SFU/**']

jobs:
  signalling-server-image:
    if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            sparse-checkout: 'SFU'
            sparse-checkout-cone-mode: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: pixelstreamingunofficial
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the SFU container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'pixelstreamingunofficial/pixel-streaming-sfu:5.5'
          push: true
          file: SFU/Dockerfile
          
